### PR TITLE
Fix updating QUrl query parameters with Qt5.

### PR DESCRIPTION
**Pull request by dreamer-dead**
- Add QUrlQueryHelper for compatibility with Qt5.
	- Use QUrlQueryHelper class and remove Qt5 version ifdefs.

When I tried to build Minitube with Qt5.4 I got some compilation errors.
After fixing them I realized that some query parameters didn't contain the Google API key.
With this pull-request I'm trying to fix both issues. Could you take a look please?

### CODE REVIEW

**Comment by flaviotordini** [comment]
Thanks for the big patch! Your helper is actually cleaner than my ifdefs all over the place. What was the issue with the API key?

**Comment by dreamer-dead** [comment]
There are some lines with code like
QUrlQuery url;

It should be

**Comment by flaviotordini** [comment]
True. I'm merging your pull request, thanks.

**Comment by dreamer-dead** [comment]
Also what do you think about enabling C++11 for Minitube?
Sometimes it can be quite useful and should be more effective, especially for latest Qt releases with move constructor support and etc.

**Comment by flaviotordini** [comment]
No strong opinion about that.

**Pull request merged**
